// <auto-generated />
using CookieStandAspNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookieStandAspNet.Migrations
{
    [DbContext(typeof(CookieStandDbContext))]
    [Migration("20230110040936_updatedcookie")]
    partial class updatedcookie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CookieStandAspNet.Models.CookieStand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Average_Cookies_Per_Sale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Maximum_Customers_Per_Hour")
                        .HasColumnType("int");

                    b.Property<int>("Minimum_Customers_Per_Hour")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CookieStand");

                    b.HasData(
                        new
                        {
                            Id = "3aa1e0ec-0cc6-4d88-bfcd-4cb85cd6caae",
                            Average_Cookies_Per_Sale = 2.5m,
                            Description = "",
                            Location = "Barcelona",
                            Maximum_Customers_Per_Hour = 7,
                            Minimum_Customers_Per_Hour = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
